#!/usr/bin/env node

/**
 * This script generates TypeScript code from ANTLR grammar files
 * It's used during the OpenSearch Dashboards bootstrap process
 */

const { execSync, exec } = require('child_process');
const path = require('path');
const fs = require('fs');

// Paths
const GRAMMAR_DIR = path.resolve(__dirname, '../../src/plugins/data/public/antlr/opensearch_ppl/grammar');
const OUTPUT_DIR = path.resolve(__dirname, '../src/ppl/generated');

// Check if ANTLR tool is installed
function checkAntlrInstallation() {
  try {
    execSync('antlr4 -version', { stdio: 'pipe' });
    return true;
  } catch (error) {
    return false;
  }
}

// Check if grammar files exist
function checkGrammarFiles() {
  const lexerPath = path.join(GRAMMAR_DIR, 'OpenSearchPPLLexer.g4');
  const parserPath = path.join(GRAMMAR_DIR, 'OpenSearchPPLParser.g4');
  
  if (!fs.existsSync(lexerPath) || !fs.existsSync(parserPath)) {
    console.error(`Grammar files not found in ${GRAMMAR_DIR}`);
    console.error('Expected files:');
    console.error(`- ${lexerPath}`);
    console.error(`- ${parserPath}`);
    return false;
  }
  
  return true;
}

// Create mock files if ANTLR is not installed
function createMockFiles() {
  console.log('Creating mock ANTLR-generated files...');
  
  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }
  
  // Create mock lexer file
  const mockLexerContent = `
/*
 * Generated by ANTLR 4 (mock)
 */
import { CharStream, Token, TokenSource } from 'antlr4ng';

export class OpenSearchPPLLexer implements TokenSource {
  constructor(input: CharStream) {
    console.log('[PPL Lexer] Created with input');
  }
  
  nextToken(): Token { return {} as Token; }
  get line(): number { return 1; }
  get column(): number { return 0; }
  get sourceName(): string { return 'PPL'; }
  get inputStream(): CharStream { return {} as CharStream; }
  get tokenFactory(): any { return null; }
}
`;
  
  // Create mock parser file
  const mockParserContent = `
/*
 * Generated by ANTLR 4 (mock)
 */
import { ANTLRErrorListener, CommonTokenStream, Parser } from 'antlr4ng';

export class OpenSearchPPLParser {
  constructor(tokenStream: CommonTokenStream) {
    console.log('[PPL Parser] Created with token stream');
  }
  
  removeErrorListeners(): void {
    console.log('[PPL Parser] Removed error listeners');
  }
  
  addErrorListener(listener: ANTLRErrorListener): void {
    console.log('[PPL Parser] Added error listener');
  }
  
  root(): void {
    console.log('[PPL Parser] Parsing root rule');
  }
}
`;
  
  fs.writeFileSync(path.join(OUTPUT_DIR, 'OpenSearchPPLLexer.ts'), mockLexerContent);
  fs.writeFileSync(path.join(OUTPUT_DIR, 'OpenSearchPPLParser.ts'), mockParserContent);
  
  console.log('Mock files created successfully!');
}

// Main function
async function main() {
  console.log('ANTLR Code Generation for PPL');
  console.log('============================');
  
  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }
  
  // Check if ANTLR is installed
  const antlrInstalled = checkAntlrInstallation();
  if (!antlrInstalled) {
    console.warn('ANTLR tool not found. To install:');
    console.warn('npm install -g antlr4-tools');
    console.warn('Creating mock files instead...');
    createMockFiles();
    return;
  }
  
  // Check if grammar files exist
  const grammarFilesExist = checkGrammarFiles();
  if (!grammarFilesExist) {
    console.warn('Creating mock files instead...');
    createMockFiles();
    return;
  }
  
  // ANTLR command
  const generateCommand = `antlr4 -Dlanguage=TypeScript -visitor -o ${OUTPUT_DIR} ${GRAMMAR_DIR}/OpenSearchPPLLexer.g4 ${GRAMMAR_DIR}/OpenSearchPPLParser.g4`;
  
  console.log('Generating ANTLR TypeScript code...');
  console.log(generateCommand);
  
  try {
    execSync(generateCommand, { stdio: 'inherit' });
    console.log('ANTLR TypeScript code generated successfully!');
  } catch (error) {
    console.error('Error generating ANTLR TypeScript code:', error);
    console.warn('Creating mock files instead...');
    createMockFiles();
    return;
  }
  
  // Fix imports in generated files
  console.log('Fixing imports in generated files...');
  
  const files = fs.readdirSync(OUTPUT_DIR).filter(file => file.endsWith('.ts'));
  
  files.forEach(file => {
    const filePath = path.join(OUTPUT_DIR, file);
    let content = fs.readFileSync(filePath, 'utf8');
    
    // Replace antlr4ts imports with antlr4ng
    content = content.replace(/from 'antlr4ts'/g, "from 'antlr4ng'");
    content = content.replace(/from 'antlr4ts\/CommonTokenStream'/g, "from 'antlr4ng'");
    content = content.replace(/from 'antlr4ts\/Token'/g, "from 'antlr4ng'");
    content = content.replace(/from 'antlr4ts\/ParserRuleContext'/g, "from 'antlr4ng'");
    content = content.replace(/from 'antlr4ts\/tree'/g, "from 'antlr4ng'");
    content = content.replace(/from 'antlr4ts\/Lexer'/g, "from 'antlr4ng'");
    content = content.replace(/from 'antlr4ts\/Parser'/g, "from 'antlr4ng'");
    content = content.replace(/from 'antlr4ts\/atn'/g, "from 'antlr4ng'");
    content = content.replace(/from 'antlr4ts\/misc'/g, "from 'antlr4ng'");
    
    fs.writeFileSync(filePath, content);
  });
  
  console.log('Imports fixed successfully!');
  console.log('ANTLR code generation complete!');
}

// Run the main function
main().catch(error => {
  console.error('Unhandled error:', error);
  process.exit(1);
});